port = "8080"
log_level = "debug"
database_url = "./filin.db"
web_cover_path = "/static/img/covers/"
smtp_host = "smtp.gmail.com"
smtp_port = "587"
smtp_login = "shop.filin.2021@gmail.com"
smtp_password = "qb179321"
primary_key = "e155e5cd-34a2-4795-8b68-f1b7bf046082"